apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectname
  namespace: kube-public
  labels:
    app: projectname
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectname
  template:
    metadata:
      labels:
        app: projectname
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: ram
                operator: In
                values:
                - 8g
            weight: 100
      containers:
        - name: projectname
          image: JOB_NAME:BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: "TZ"
              value: "Asia/Shanghai"
          volumeMounts:
            - name: pvc
              mountPath: /data
              subPath: projectname/data
            - name: cm
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: projectname-pvc
        - name: cm
          configMap:
            name: projectname-cm
            items:
              - key: "nginx.conf"
                path: "nginx.conf"